### ISSUE TITLE
Set up a deployment pipeline for app.pdap.io

### ISSUE THREAD

**Issue by josh-chamberlain** [Police-Data-Accessibility-Project/PDAP-Data-Sources-App#3]
This was FTP'd to the server by Eric from his repo; now it has its own repo.

- Apparently there are some .env vars that shouldn't be touched; what are they? How are they configured?
- Can we set this up to automatically deploy when new code is merged, like the `gatsby-pdap-frontpage` repo?

**Comment by jlintag** [comment]
Is there a status endpoints that I could hit to determine whether the service is running?

And dumping server error logs when DEBUG=True would be helpful; I can't determine what's causing issues in deployment since it seems it deploys fine but accessing the site isn't working.

https://app.pdap.dev/

**Comment by josh-chamberlain** [comment]
@EricTurner3 not sure if you saw this ↑

**Comment by EricTurner3** [comment]
@jlintag , for whatever reason I am just now seeing this. You can find the .env variables directly on the machine in `/var/www/html/app/pdap/pdap/.env`. Or I can PM them to you on Discord. 

It's an actual VPS and not one of the apps, it required manual setup with Nginx and Gunicorn so trying to use the app portion probably will not work.

I wrote down some information on how we might be able to do it, if we setup a webhook that then runs a script this may work: https://www.notion.so/pdap/App-Box-Technical-Documentation-2cd6c8129fcf4eaeaa5fd3fac3041572#649089944a1543f9ba34194de02f4961
